import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLocale = 'en';
  bool _isLoading = true;

  String get currentLocale => _currentLocale;
  bool get isLoading => _isLoading;

  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLocale = prefs.getString('locale') ?? 'en';
    _isLoading = false;
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) async {
    if (_currentLocale == languageCode) return;
    _currentLocale = languageCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('locale', languageCode);
    notifyListeners();
  }

  void toggleLanguage() {
    setLanguage(_currentLocale == 'en' ? 'hi' : 'en');
  }

  String translate(String key) {
    if (_currentLocale == 'hi' && _hindiTranslations.containsKey(key)) {
      return _hindiTranslations[key]!;
    }
    return _englishTranslations[key] ?? key;
  }

  static const Map<String, String> _englishTranslations = {
    // Landing Screen
    'how_would_you_like_to_use': 'How would you like to use the platform today?',
    'i_want_to_donate_food': 'I want to Donate Food',
    'donate_food_desc': 'For restaurants, bakeries, and caterers with surplus.',
    'i_want_to_rescue_food': 'I want to Rescue Food',
    'rescue_food_desc': 'For NGOs, shelters, and community kitchens.',
    'already_have_an_account': 'Already Have an Account?',
    'home': 'Home',
    'mission': 'Mission',
    'our_working': 'Our Working',
    'sign_in': 'Sign In',
    'trusted_network': 'TRUSTED DONATION & RELIEF NETWORK',
    'hero_title': 'Share your extra things to help others.',
    'hero_subtitle': 'ManavSeva connects generous people with trusted NGOs to share food, clothes, books, toys and medical instruments with those who need them most.',
    'register_ngo': 'Register as NGO',
    'register_donor': 'Register as Donor',
    'share_what_you_can': 'Share what you can',
    'every_donation_helps': 'Every donation can\nhelp someone in need.',
    'small_acts': '"Small acts.',
    'big_impact': 'Big impact."',
    'needs_matched': 'Needs matched\nwith care',
    'connecting_responsibly': 'Connecting donors and\nNGOs responsibly.',
    'pickup_arranged': 'Pickup arranged\nwith care',
    'pickup_desc': 'We pick up and\ndeliver thoughtfully.',
    'hope_travels': 'Hope travels\nfurther',
    'hope_desc': 'Essentials reach\nthe right hands.',
    'how_it_works': 'HOW IT WORKS',
    'from_extra_to_smile': 'From your extra to someone\'s smile',
    'post_donation': 'Post Donation',
    'post_donation_desc': 'Add extra items one time or set a recurring pickup.',
    'find_nearest_ngo': 'Find Nearest NGO',
    'find_ngo_desc': 'The platform matches the donation with a nearby trusted NGO.',
    'claim_pickup': 'Claim and Pick Up',
    'claim_pickup_desc': 'NGOs claim items and arrange pickup while tracking the process.',
    'our_mission': 'Our Mission',
    'mission_title': 'Connecting extra supplies with people in need.',
    'mission_desc': 'ManavSeva connects kind donors with trusted NGOs so food, clothes, books, toys, and medical supplies reach people who need them most.',

    // Common Auth
    'email_address': 'Email Address',
    'password': 'Password',
    'login': 'Login',
    'sign_up': 'Sign Up',
    'continue_google': 'Continue with Google',
    'back': 'Back',
    'proceed_details': 'Proceed to Details',
    'send_otp': 'Send OTP',
    'verify_register': 'Verify & Register',
    'otp_check': 'Security Check',
    'otp_desc': 'Enter the 6-digit verification code sent to\nyour registered phone number.',

    // NGO Auth
    'ngo_welcome': 'Welcome back, NGO Partner',
    'ngo_login_desc': 'Login to manage claims, track pickups, and monitor your impact.',
    'create_ngo_account': 'Create NGO Account',
    'create_ngo_desc': 'Join our network to receive donations and help your community.',
    'dont_have_account': 'Don\'t have an account?',
    'already_have_account': 'Already have an account?',
    'switch_to_donor': 'Switch to Donor registration',
    'org_profile': 'Organization Profile',
    'org_desc': 'Provide your registered NGO details and verification info.',
    'ngo_name': 'NGO Name / Organization Name',
    'contact_mobile': 'Contact Mobile',
    'darpan_id': 'DARPAN ID (Optional)',
    'hq_location': 'HEADQUARTERS LOCATION',
    'autofill_location': 'Auto-fill Location',
    'operating_state': 'Operating State',
    'district_region': 'District / Region',
    'street_address': 'Street Address',
    'pinpoint_location': 'Pinpoint Exact Location',
    'required': 'REQUIRED',
    'drag_pin': 'Drag pin to exact location',

    // Supplier Auth
    'donor_welcome': 'Welcome back, Generous Donor',
    'donor_login_desc': 'Login to post donations and track your impact.',
    'create_donor_account': 'Create Donor Account',
    'create_donor_desc': 'Join our network to easily share extra supplies with those in need.',
    'switch_to_ngo': 'Switch to NGO registration',
    'donor_profile': 'Donor Profile',
    'donor_desc': 'Provide your details and pickup location info.',
    'full_name': 'Full Name / Organization Name',
    'pickup_location': 'PICKUP LOCATION',

    // Side Menus
    'dashboard': 'Dashboard',
    'donations_dhundho': 'Donations Dhundho',
    'aapke_claims': 'Aapke Claims',
    'team': 'Team',
    'settings': 'Settings',
    'sign_out': 'Sign Out',
    'post_new_donation': 'Post New Donation',
    'my_donations': 'My Donations',
    'history': 'History',
    'menu_hide': 'Hide Menu',
    'admin': 'Admin',
    'ngo_portal': 'NGO PORTAL',
    'donor_portal': 'DONOR PORTAL',

    // Dashboards
    'good_morning': 'Good Morning,',
    'active_claims': 'Active Claims',
    'completed_pickups': 'Completed Pickups',
    'total_impact': 'Total Impact',
    'people_helped': 'People Helped',
    'recent_donations': 'Recent Donations',
    'no_donations_yet': 'No donations yet.',
    'view_all': 'View All',
    'status_pending': 'Pending',
    'status_accepted': 'Accepted',
    'status_completed': 'Completed',
    'items_donated': 'Items Donated',
    'kg_food': 'kg Food',
    'active_posts': 'Active Posts',
    'available_donations': 'Available Donations',
    'browse_donations_desc': 'Browse and claim available surplus food near you.',
    'search_donations': 'Search donations or suppliers...',
    'clear_filters': 'Clear Filters',
    'no_donations_found': 'No donations found',
    'try_adjusting_search': 'Try adjusting your search or filters.',
    'claim_donation': 'Claim Donation',
    'successfully_claimed': 'Successfully claimed!',
    'view_details': 'View Details',
    'my_claims_pickups': 'My Claims & Pickups',
    'track_manage_claims': 'Track and manage your claimed food donations.',
    'no_claims_found': 'No Claims Found',
    'donation_history': 'Donation History',
    'view_track_past': 'View and track your past food donations.',
    'history_appear_here': 'Your donation history will appear here once donations are completed.',
    'team_members': 'Team Members',
    'manage_team': 'Manage your team and assignments',
    'add_new_employee': 'Add New Employee',
    'create_employee_account': 'Create Employee Account',
    'add_team_members': 'Add your team members to help with deliveries.',
    'no_employees_found': 'No employees found',
    'mobile': 'MOBILE',
    'added': 'ADDED',
    'action': 'ACTION',
    'assign_employee': 'Assign Employee',
    'post_donation_title': 'Post Donation',
    'upload_photo': 'Upload Photo',
    'show_food_donating': 'Show the food you are donating',
    'category': 'Category',
    'please_fill_fields': 'Please fill all fields',
    'donation_posted': 'Donation posted successfully!',
    'status': 'STATUS',
    'cancel': 'Cancel',
    'for_ngos': 'FOR NGOs',
    'find_supplies_faster': 'Find supplies faster, serve people better.',
    'find_nearby_trusted': 'Find nearby trusted donations, claim items quickly, and arrange pickup to reach communities in need.',
    'nearby_matches': 'Nearby Matches',
    'get_relevant_donations': 'Get relevant donations near your location.',
    'fast_claim': 'Fast Claim',
    'claim_instantly': 'Claim items instantly and secure them.',
    'pickup_support': 'Pickup Support',
    'medical_supplies': 'Medical Supplies',
    'coordinate_pickup': 'Coordinate pickup with ease.',
    'for_donors': 'FOR DONORS',
    'turn_extra_items': 'Turn extra items into real help.',
    'list_your_extra': 'List your extra things in minutes, track requests in real time, and schedule a pickup that works for you.',
    'easy_listing': 'Easy Listing',
    'add_items_once': 'Add items once in just a few steps.',
    'scheduled_pickup': 'Scheduled Pickup',
    'choose_a_time': 'Choose a time and we\'ll help arrange pickup.',
    'track_impact': 'Track Impact',
    'see_how_your_items': 'See how your items create impact.',
    'verified_ngos': 'Verified NGOs',
    'verified_ngos_desc': 'All our partner NGOs are thoroughly vetted to ensure your trust is maintained.',
    'izzat_ke_saath': 'Help with Dignity',
    'izzat_ke_saath_desc': 'We ensure that donations are distributed with the utmost care and respect.',
    'testimonial_quote': 'ManavSeva ne hamare liye wapas dena simple bana diya. Hamare extra items ab un communities tak pahunchte hain jinhe sach mein zaroorat hai.',
    'terms_of_service': 'Terms of Service',
    'privacy_policy': 'Privacy Policy',
    'partner_portal': 'Partner Portal',
  };

  static const Map<String, String> _hindiTranslations = {
    // Landing Screen
    'how_would_you_like_to_use': 'Aaj aap platform ka upyog kaise karna chahenge?',
    'i_want_to_donate_food': 'Main Khana Donate Karna Chahta Hu',
    'donate_food_desc': 'Surplus wale restaurants, bakeries, aur caterers ke liye.',
    'i_want_to_rescue_food': 'Main Khana Rescue Karna Chahta Hu',
    'rescue_food_desc': 'NGOs, shelters, aur community kitchens ke liye.',
    'already_have_an_account': 'Kya aapka pehle se account hai?',
    'home': 'Home',
    'mission': 'Mission',
    'our_working': 'Hamara Kaam',
    'sign_in': 'Sign In',
    'trusted_network': 'BHAROSEMAND DONATION & RELIEF NETWORK',
    'hero_title': 'Dusro ki madad ke liye apni extra cheezein share karein.',
    'hero_subtitle': 'ManavSeva acche logo ko bharosemand NGOs se jodta hai taaki khana, kapde, kitabein, khilone aur medical saaman zarooratmand logo tak pahuch sake.',
    'register_ngo': 'NGO ke roop mein Register karein',
    'register_donor': 'Donor ke roop mein Register karein',
    'share_what_you_can': 'Jo ho sake share karein',
    'every_donation_helps': 'Har donation kisi zarooratmand\nki madad kar sakta hai.',
    'small_acts': '"Chote kaam.',
    'big_impact': 'Bada asar."',
    'needs_matched': 'Zarooraton ka\nsahi milaan',
    'connecting_responsibly': 'Donors aur NGOs ko\nzimmedari se jodna.',
    'pickup_arranged': 'Pickup ki\nsuvidha',
    'pickup_desc': 'Hum saaman uthate hain aur\nsurakshit pahunchate hain.',
    'hope_travels': 'Umeed aage\nbadhti hai',
    'hope_desc': 'Zaroori cheezein\nsahi haathon tak pahunchti hain.',
    'how_it_works': 'YAH KAISE KAAM KARTA HAI',
    'from_extra_to_smile': 'Aapki extra cheez se kisi ki muskaan tak',
    'post_donation': 'Donation Post karein',
    'post_donation_desc': 'Ek baar ke liye extra cheezein jodein ya baar-baar pickup set karein.',
    'find_nearest_ngo': 'Paas ka NGO khojein',
    'find_ngo_desc': 'Platform aapke donation ko paas ke bharosemand NGO se milata hai.',
    'claim_pickup': 'Claim karein aur Pickup karein',
    'claim_pickup_desc': 'NGOs cheezon ka claim karte hain aur process track karte hue pickup arrange karte hain.',
    'our_mission': 'Hamara Mission',
    'mission_title': 'Zarooratmand logo ke saath extra saaman jodna.',
    'mission_desc': 'ManavSeva acche donors ko bharosemand NGOs se jodta hai taaki khana, kapde, kitabein, khilone aur medical saaman un logo tak pahunche jinhe inki sabse zyada zaroorat hai.',

    // Common Auth
    'email_address': 'Email Address',
    'password': 'Password',
    'login': 'Login karein',
    'sign_up': 'Sign Up karein',
    'continue_google': 'Google se aage badhein',
    'back': 'Peeche jaayein',
    'proceed_details': 'Details bharein',
    'send_otp': 'OTP Bhejein',
    'verify_register': 'Verify & Register karein',
    'otp_check': 'Security Check',
    'otp_desc': 'Aapke registered phone number par bheja gaya 6-digit verification code daalein.',

    // NGO Auth
    'ngo_welcome': 'Wapas swagat hai, NGO Partner',
    'ngo_login_desc': 'Claims manage karne, pickups track karne aur apna asar dekhne ke liye login karein.',
    'create_ngo_account': 'NGO Account banayein',
    'create_ngo_desc': 'Donations lene aur apni community ki madad karne ke liye hamare network se judein.',
    'dont_have_account': 'Account nahi hai?',
    'already_have_account': 'Pehle se account hai?',
    'switch_to_donor': 'Donor registration par jaayein',
    'org_profile': 'Organization Profile',
    'org_desc': 'Apne registered NGO ki details aur verification info daalein.',
    'ngo_name': 'NGO ka Naam / Organization ka Naam',
    'contact_mobile': 'Contact Mobile Number',
    'darpan_id': 'DARPAN ID (Optional)',
    'hq_location': 'HEADQUARTERS KI LOCATION',
    'autofill_location': 'Location apne aap bharein',
    'operating_state': 'Operating State',
    'district_region': 'District / Region',
    'street_address': 'Street Address',
    'pinpoint_location': 'Sahi Location Pinpoint karein',
    'required': 'ZAROORI',
    'drag_pin': 'Sahi location par pin ko drag karein',

    // Supplier Auth
    'donor_welcome': 'Wapas swagat hai, Generous Donor',
    'donor_login_desc': 'Donations post karne aur apna asar track karne ke liye login karein.',
    'create_donor_account': 'Donor Account banayein',
    'create_donor_desc': 'Zarooratmand logo ke saath apni extra cheezein share karne ke liye hamare network se judein.',
    'switch_to_ngo': 'NGO registration par jaayein',
    'donor_profile': 'Donor Profile',
    'donor_desc': 'Apni details aur pickup location info daalein.',
    'full_name': 'Pura Naam / Organization ka Naam',
    'pickup_location': 'PICKUP KI LOCATION',

    // Side Menus
    'dashboard': 'Dashboard',
    'donations_dhundho': 'Donations Dhundho',
    'aapke_claims': 'Aapke Claims',
    'team': 'Team',
    'settings': 'Settings',
    'sign_out': 'Sign Out',
    'post_new_donation': 'Naya Donation Post karein',
    'my_donations': 'Mere Donations',
    'history': 'History',
    'menu_hide': 'Menu Chupao',
    'admin': 'Admin',
    'ngo_portal': 'NGO PORTAL',
    'donor_portal': 'DONOR PORTAL',

    // Dashboards
    'good_morning': 'Subah Bakhair,',
    'active_claims': 'Active Claims',
    'completed_pickups': 'Mukammal Pickups',
    'total_impact': 'Kul Asar',
    'people_helped': 'Madad kiye gaye log',
    'recent_donations': 'Haal hi ke Donations',
    'no_donations_yet': 'Abhi tak koi donation nahi.',
    'view_all': 'Sabhi dekhein',
    'status_pending': 'Pending',
    'status_accepted': 'Maan liya gaya',
    'status_completed': 'Pura ho gaya',
    'items_donated': 'Items Donate kiye',
    'kg_food': 'kg Khana',
    'active_posts': 'Active Posts',
    'available_donations': 'Available Donations',
    'browse_donations_desc': 'Aas paas ka surplus khana browse karein aur claim karein.',
    'search_donations': 'Donations ya suppliers dhundein...',
    'clear_filters': 'Filters Hatayein',
    'no_donations_found': 'Koi donations nahi mile',
    'try_adjusting_search': 'Apne search ya filters ko thoda badalkar dekhein.',
    'claim_donation': 'Donation Claim karein',
    'successfully_claimed': 'Successfully claim ho gaya!',
    'view_details': 'Details dekhein',
    'my_claims_pickups': 'Mere Claims aur Pickups',
    'track_manage_claims': 'Apne claim kiye hue food donations ko track aur manage karein.',
    'no_claims_found': 'Koi claims nahi mile',
    'donation_history': 'Donation History',
    'view_track_past': 'Apne pichle food donations dekhein aur track karein.',
    'history_appear_here': 'Jab donations complete ho jayenge tab yahan show honge.',
    'team_members': 'Team Members',
    'manage_team': 'Apni team aur assignments ko manage karein',
    'add_new_employee': 'Naya Employee jodein',
    'create_employee_account': 'Employee Account banayein',
    'add_team_members': 'Deliveries mein help ke liye apni team members ko jodein.',
    'no_employees_found': 'Koi employee nahi mila',
    'mobile': 'MOBILE',
    'added': 'ADDED',
    'action': 'ACTION',
    'assign_employee': 'Employee Assign karein',
    'post_donation_title': 'Donation Post karein',
    'upload_photo': 'Photo Upload karein',
    'show_food_donating': 'Jo khana aap donate kar rahe hain uski photo lagayein',
    'category': 'Category',
    'please_fill_fields': 'Kripya sabhi fields bharein',
    'donation_posted': 'Donation successfully post ho gaya!',
    'status': 'STATUS',
    'cancel': 'Cancel',
    'for_ngos': 'NGOs KE LIYE',
    'find_supplies_faster': 'Zaroorat ka saaman jaldi payein, logon ki behtar madad karein.',
    'find_nearby_trusted': 'Aas paas trusted donations dhoondein, jaldi claim karein, aur zaruratmand logon tak pahunchane ke liye pickup arrange karein.',
    'nearby_matches': 'Aas Paas ke Matches',
    'get_relevant_donations': 'Apni location ke paas relevant donations dekhein.',
    'fast_claim': 'Jaldi Claim',
    'claim_instantly': 'Items ko instantly claim aur secure karein.',
    'pickup_support': 'Pickup Support',
    'medical_supplies': 'Medical Supplies',
    'coordinate_pickup': 'Aasani se pickup coordinate karein.',
    'for_donors': 'DONORS KE LIYE',
    'turn_extra_items': 'Apne extra items ko asli madad mein badlein.',
    'list_your_extra': 'Apni extra cheezein minutes mein list karein, requests ko real-time mein track karein, aur apne hisaab se pickup schedule karein.',
    'easy_listing': 'Aasan Listing',
    'add_items_once': 'Sirf kuch steps mein items add karein.',
    'scheduled_pickup': 'Scheduled Pickup',
    'choose_a_time': 'Time chunein aur hum pickup mein madad karenge.',
    'track_impact': 'Impact Track Karein',
    'see_how_your_items': 'Dekhein aapke items se kya farq padta hai.',
    'verified_ngos': 'Verified NGOs',
    'verified_ngos_desc': 'Hamare saare partner NGOs puri tarah se check kiye gaye hain taaki aapka bharosa bana rahe.',
    'izzat_ke_saath': 'Izzat Ke Saath Madad',
    'izzat_ke_saath_desc': 'Hum ensure karte hain ki donations care aur respect ke saath distribute hon.',
    'testimonial_quote': 'ManavSeva ne hamare liye wapas dena simple bana diya. Hamare extra items ab un communities tak pahunchte hain jinhe sach mein zaroorat hai.',
    'terms_of_service': 'Terms of Service',
    'privacy_policy': 'Privacy Policy',
    'partner_portal': 'Partner Portal',
  };
}
