// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsYSlFzKk6CzzB26Q1HIPdkLHlJN0xG2s',
    appId: '1:830664055084:android:ee0cc7746b23a0a0243489',
    messagingSenderId: '830664055084',
    projectId: 'surplusshare-01',
    storageBucket: 'surplusshare-01.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGaG1KS-2avGqRQvcKoPX4BxC7hHC6YRA',
    appId: '1:830664055084:ios:531e08e3c0e5a1a3243489',
    messagingSenderId: '830664055084',
    projectId: 'surplusshare-01',
    storageBucket: 'surplusshare-01.firebasestorage.app',
    androidClientId: '830664055084-nev6soue1nb86gdb9qedn7nso0vkgari.apps.googleusercontent.com',
    iosClientId: '830664055084-rlehvijljjh6s09f6o179qtl7f51q71k.apps.googleusercontent.com',
    iosBundleId: 'com.surplusshare.surplusShare',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6HKifZZpjLyiPvGjlxfwoneLlp1vGP38',
    appId: '1:830664055084:web:cefac0c19006fcb2243489',
    messagingSenderId: '830664055084',
    projectId: 'surplusshare-01',
    authDomain: 'surplusshare-01.firebaseapp.com',
    storageBucket: 'surplusshare-01.firebasestorage.app',
    measurementId: 'G-XJS6WKPE2J',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGaG1KS-2avGqRQvcKoPX4BxC7hHC6YRA',
    appId: '1:830664055084:ios:531e08e3c0e5a1a3243489',
    messagingSenderId: '830664055084',
    projectId: 'surplusshare-01',
    storageBucket: 'surplusshare-01.firebasestorage.app',
    androidClientId: '830664055084-nev6soue1nb86gdb9qedn7nso0vkgari.apps.googleusercontent.com',
    iosClientId: '830664055084-rlehvijljjh6s09f6o179qtl7f51q71k.apps.googleusercontent.com',
    iosBundleId: 'com.surplusshare.surplusShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6HKifZZpjLyiPvGjlxfwoneLlp1vGP38',
    appId: '1:830664055084:web:cefac0c19006fcb2243489',
    messagingSenderId: '830664055084',
    projectId: 'surplusshare-01',
    authDomain: 'surplusshare-01.firebaseapp.com',
    storageBucket: 'surplusshare-01.firebasestorage.app',
    measurementId: 'G-XJS6WKPE2J',
  );
}
